### ISSUE TITLE
Neminifikovane scripty v DEVELOPMENT

### ISSUE THREAD

**Issue by yarri** [atk14/Atk14Skelet#12]
V DEVELOPMENT potrebujeme neminifikovane scripty

Viz 04ca2feaa4b1f5af9bf7bb17d34e052ba0be43e7

**Comment by yarri** [comment]
Pomuze to vyresit @mattez?

**Comment by bganicky** [comment]
S pouzitim source map nejsou potreba.

**Comment by yarri** [comment]
Bezva! Zavru to.
