### ISSUE TITLE
Odstranit NPM WARNs

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Skelet#16]
NPM aktualne hlasi nasledujici upozorneni:

``` bash
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global jshint@2.8.0 should be installed with -g
```

je tedy potreba:
- pouzit **_gulp-cssnano**_ misto _gulp-minify-css_
- pouzit novy **_lodash@^3.0.0**_ (zeptat se @beshe zda je potreba)
- doprucit instalaci **_jsonlint**_ a **_jshint**_ globalne do systemu uzivatele, aby se neinstaloval pro kazdy projekt zvlast.

**Comment by yarri** [comment]
Zavírám. Toto nás už v Atk14Skeletu nepálí...
