### ISSUE TITLE
"bower_components" directory permissions

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Skelet#3]
@bganicky : Jedná se o **branch GULP** a bowerem vytvářený adresář "/bower_components"
Protože celý adresář "bower_components" resp. "bower_components/bootrsrap" **nemá práva k prohlížení** přes browser, nemůžu využít **sourcemaps** v _Inspektoru_ a zobrazit si použité LESS soubory z Bootstrapu.

Takže pro development by to chtělo mít tenhle adresář přístupný.
Dáme to? nebo jak?

**Comment by yarri** [comment]
Ahoj, udelej si pro ten adresar vyjimku v .htaccess podobne, jako to ma
adresar public. Lomitko budes muset oescapovat zpetnym lomitkem.

J.

**Comment by mattez** [comment]
Ahoj Jarku,
diky moc za info. Pridal jsem vyjimku, data z adresare se mi zobrazuji. Nevadi ze to v htaccessu zustane i pro produkci?  tam ten adresar IMHO ani nebude (pac neni verzovany). Budem to nejak resit?

BTW Ale porad mi nerad FF hlasi:
![screenshot from 2015-06-21 16 48 44](https://cloud.githubusercontent.com/assets/143115/8272066/7b030d68-1835-11e5-8d98-6e067b00ad8a.png)
Jsou ty URL stejne, ne? Nebo spatne vidim?
Tenhle problem uz je off-topic. Asi to bude spis problem FF.

**Comment by bganicky** [comment]
To bude spis chyba s blbe vygenerovanou source mapou, kde neopovidaji cesty.

Update:
Hmm, tak to spis ne. Cesty jsou dobre.

**Comment by yarri** [comment]
Nevadi, ze to tak v produkci zustane. Pokud tam nebude, tak se proste 
vrati 404 Not Found odpoved.

J.

**Comment by yarri** [comment]
Toto zavírám. Bower už nepoužíváme...
