### ISSUE TITLE
Premisteni atk14.js do Bower repozitare.

### ISSUE THREAD

**Issue by bganicky** [atk14/Atk14Skelet#4]
Yarri, muzes prosim pod atk14 organizaci zalozit repozitar atk14.js a dat mi tam commit access? Je na case z atk14.js udelat bower componentu a instalovat ji stejne jako ostatni dependencies. Takhle tam porad nekde strasi, kde nema co delat.

**Comment by yarri** [comment]
Je to tady: https://github.com/atk14/Atk14Js

J.
