### ISSUE TITLE
locale, gettext: script nevytvari adresarovou strukturu

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Skelet#8]
- Chci udelat novou jazykovou verzi (napr slovenskou)
- Pridam do locale.yml jazyk
- jdu do /locale/
- generuji Gettext files - jedu dle README
- NEvytvori se nova adresar. struktura pro novy jazyky (/locale/sk_SK/LC_MESSAGES/)

kdyz vytvoris adresare rucne, je to OK.

Bud to dat nekam do README (at uzivatel vi, ze musi vytvorit adr. rucne) nebo upravit script tak, aby adr. vytvoril sam.

**Comment by yarri** [comment]
Opraveno. Neexistujici adresar se vytvori automaticky.

**Comment by yarri** [comment]
6ea57dbffd97229b9e6f371fb1d0d2415dc14048
9b760e4a02c42f96a9870ff53b43b824896e247e
