### ISSUE TITLE
locale/Makefile: Nemodifikuj PO soubory, pokud se v prekladech nic nezmenilo.

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Skelet#9]
Pokud se nyni projede proces generovani PO souboru, i presto, ze se preklady nezmenili, v PO souboru se zmeni pouze "POT-Creation-Date" v hlavicce, např:

``` diff
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2015-09-15 15:42+0200\n"
+"POT-Creation-Date: 2015-10-21 13:53+0200\n"
 "PO-Revision-Date: 2015-09-15 15:43+0100\n"
```

To je naprd kvuli GITu a DIFFovani.
Dalo by se to prosim nejak vyresit?
Dikec.

**Comment by mattez** [comment]
Soubor, který vznikne po projeti zdrojaku se automaticky jmenuje messages.po, ale měl by se hned potom přejmenovat na .pot. Viz gnu.org [Making the PO Template File](http://www.gnu.org/software/gettext/manual/gettext.html#Making-the-PO-Template-File).

> xgettext creates a file named domainname.po. You should then rename it to domainname.pot. (Why doesn’t xgettext create it under the name domainname.pot right away? The answer is: for historical reasons. When xgettext was specified, the distinction between a PO file and PO file template was fuzzy, and the suffix ‘.pot’ wasn’t in use at that time.) 

Při akci "merge" ho přejmenovat na messages.po, aktuálně v locale/Makefile asi řádek 37:

```
-cp messages.po $(1)/LC_MESSAGES;
```

v _locale/Makefile_ je taky akce "clear", která nakonec, krom jineho, maže i zdrojový (prázdný) template messages.po(t)
Co jej tam nechat a porovnávat ho při příštím generovaní, jestli je stejný nebo ne? A pokud ano může se script ukončit, protože žádné nové msgid nepřibylo.

**Comment by yarri** [comment]
Opraveno v 424fa47
